### ISSUE TITLE
Link to website

### ISSUE THREAD

**Issue by mayank-umn** [chandrikadeb7/MyOnlineStore#1]
Hi Chandrika, 
Congrats for the awesome work on github. I am really impressed. What is the link to the website? How can i run your code for Myonline store?

**Comment by chandrikadeb7** [comment]
> Hi Chandrika,
> Congrats for the awesome work on github. I am really impressed. What is the link to the website? How can i run your code for Myonline store?

Sorry I haven't deployed it yet. You can run it on localhost.
